{"trial_id": "1", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "Conv_layers", "default": null, "conditions": [], "min_value": 0, "max_value": 3, "step": 1, "sampling": "linear"}}], "values": {"Conv_layers": 3}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\SULEMAN\\anaconda3\\envs\\test2\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\SULEMAN\\anaconda3\\envs\\test2\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\SULEMAN\\anaconda3\\envs\\test2\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"C:\\Users\\SULEMAN\\anaconda3\\envs\\test2\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 232, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"C:\\Users\\SULEMAN\\anaconda3\\envs\\test2\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 164, in _try_build\n    model = self._build_hypermodel(hp)\n  File \"C:\\Users\\SULEMAN\\anaconda3\\envs\\test2\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 155, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n  File \"C:\\Users\\SULEMAN\\AppData\\Local\\Temp\\ipykernel_19172\\191692842.py\", line 13, in build_model\n    model.add(layers.Conv2D(\nNameError: name 'layers' is not defined\n"}